sudo: false
language: python
python:
  - "3.4"
  - "3.5"
before_script:
  - cp config/config.yml.dist config/config.yml
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --branch --include='src/*' -m unittest discover
after_success:
  coveralls